export const login = '/login'
export const registration = '/registration'
export const disk = '/disk'
export const forgotPassword = '/forgot-password'
export const resetPassword = '/reset-password/:id/:token'